In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("C:\\Users\\91988\\Downloads\\Coffee Cup Data.xlsx")
df.head()

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
0,-354,-245,17,245,126,93,1419,-240,-160,0,160,31/1/2019,Central,Ontario,Toronto,702,Small Market,Tea,Green Tea,Regular
1,-172,-44,61,105,128,95,725,-170,-50,50,100,31/1/2019,Atlantic,PEI,Charlottetown,315,Major Market,Espresso,Caffe Mocha,Regular
2,-117,-26,118,144,91,47,862,-120,-40,140,180,31/1/2019,West,British Columbia,Vancouver,685,Major Market,Coffee,Decaf Irish Cream,Decaf
3,-113,-27,180,207,86,64,965,-70,-10,140,150,31/1/2019,Atlantic,PEI,Charlottetown,845,Major Market,Herbal Tea,Mint,Decaf
4,-40,11,99,88,51,27,525,-30,10,80,70,31/1/2019,Atlantic,New Brunswick,Saint John,591,Small Market,Herbal Tea,Mint,Decaf

In [3]:
df.dtypes

Profit                 int64
Margin                 int64
Sales                  int64
Cost of Goods Sold     int64
Total Expenses         int64
Marketing              int64
Inventory              int64
Budget Profit          int64
Budget Margin          int64
Budget Sales           int64
Budget COGS            int64
Date                  object
Market                object
Province              object
City                  object
Store#                 int64
Market Size           object
Product Type          object
Product               object
Type                  object
dtype: object

In [4]:
df["Type"].unique()

array(['Regular', 'Decaf'], dtype=object)

In [5]:
df["Product"].unique()

array(['Green Tea', 'Caffe Mocha', 'Decaf Irish Cream', 'Mint', 'Lemon',
       'Chamomile', 'Darjeeling', 'Earl Grey', 'Caffe Latte',
       'Regular Espresso', 'Colombian', 'Amaretto', 'Decaf Espresso'],
      dtype=object)

In [6]:
df["Product Type"].unique()

array(['Tea', 'Espresso', 'Coffee', 'Herbal Tea'], dtype=object)

In [7]:
df["Market Size"].unique()

array(['Small Market', 'Major Market'], dtype=object)

In [8]:
df["Market"].unique()

array(['Central', 'Atlantic', 'West', 'North', 'Prairie'], dtype=object)

In [9]:
df["Date"].unique()

array(['31/1/2019', '28/2/2019', '31/03/2012', '31/03/2019', '30/04/2019',
       '31/05/2019', '30/06/2019', '31/07/2019', '31/08/2019',
       '30/09/2019', '31/10/2019', '30/11/2019', '31/12/2019',
       '31/01/2020', '28/02/2020', '31/03/2020', '30/04/2020',
       '31/05/2020', '30/06/2020', '31/07/2020', '31/08/2020',
       '30/09/2020', '31/10/2020', '30/11/2020', '31/12/2020'],
      dtype=object)

In [10]:
df[df["Date"] == '31/03/2012']

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
354,-340,-245,32,245,127,93,2449,-240,-160,0,160,31/03/2012,Central,Ontario,London,775,Small Market,Tea,Green Tea,Regular
355,-208,-62,63,125,146,113,1118,-190,-60,60,120,31/03/2012,Atlantic,PEI,Summerside,607,Major Market,Espresso,Caffe Mocha,Regular

In [11]:
df["Profit"].max()

778

In [12]:
df["Profit"].min()

-638

In [13]:
df["Profit"].mean()

61.097693032015066

In [14]:
df.describe(include= "all")

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
count,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248.000000,4248,4248,4248,4248,4248.000000,4248,4248,4248,4248
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,5,13,51,NaN,2,4,13,2
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31/08/2020,Atlantic,Ontario,Kelowna,NaN,Small Market,Espresso,Colombian,Regular
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177,1464,528,285,NaN,2544,1176,480,2400
mean,61.097693,104.293315,192.987524,84.433145,54.063559,31.185028,749.381356,60.913371,100.819209,175.649718,74.830508,NaN,NaN,NaN,NaN,1546.422316,NaN,NaN,NaN,NaN
std,101.708546,94.342522,151.133127,67.249769,32.352598,27.023264,661.031896,79.546123,92.602725,148.891522,66.238145,NaN,NaN,NaN,NaN,1839.763082,NaN,NaN,NaN,NaN
min,-638.000000,-302.000000,17.000000,0.000000,10.000000,0.000000,-3534.000000,-320.000000,-210.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,212.000000,NaN,NaN,NaN,NaN
25%,17.000000,52.750000,100.000000,43.000000,33.000000,13.000000,432.000000,20.000000,50.000000,80.000000,30.000000,NaN,NaN,NaN,NaN,541.000000,NaN,NaN,NaN,NaN
50%,40.000000,76.000000,138.000000,60.000000,46.000000,22.000000,619.000000,40.000000,70.000000,130.000000,50.000000,NaN,NaN,NaN,NaN,685.000000,NaN,NaN,NaN,NaN
75%,92.000000,132.000000,230.000000,100.000000,65.000000,39.000000,910.500000,80.000000,130.000000,210.000000,90.000000,NaN,NaN,NaN,NaN,1200.000000,NaN,NaN,NaN,NaN
max,778.000000,613.000000,912.000000,364.000000,190.000000,156.000000,8252.000000,560.000000,690.000000,1140.000000,450.000000,NaN,NaN,NaN,NaN,6520.000000,NaN,NaN,NaN,NaN

In [15]:
df.isnull().sum()

Profit                0
Margin                0
Sales                 0
Cost of Goods Sold    0
Total Expenses        0
Marketing             0
Inventory             0
Budget Profit         0
Budget Margin         0
Budget Sales          0
Budget COGS           0
Date                  0
Market                0
Province              0
City                  0
Store#                0
Market Size           0
Product Type          0
Product               0
Type                  0
dtype: int64

## Date

In [16]:
#dropping 354 and 355 rows

df.drop([354,355], inplace = True)

In [17]:
df[df["Date"] == '31/03/2012']

Empty DataFrame
Columns: [Profit, Margin, Sales, Cost of Goods Sold, Total Expenses, Marketing, Inventory, Budget Profit, Budget Margin, Budget Sales, Budget COGS, Date, Market, Province, City, Store#, Market Size, Product Type, Product, Type]
Index: []

In [18]:
display(df.iloc[354])

Profit                             -121
Margin                              -27
Sales                               127
Cost of Goods Sold                  154
Total Expenses                       94
Marketing                            50
Inventory                          1288
Budget Profit                      -120
Budget Margin                       -40
Budget Sales                        150
Budget COGS                         190
Date                         31/03/2019
Market                             West
Province               British Columbia
City                          Vancouver
Store#                              685
Market Size                Major Market
Product Type                     Coffee
Product               Decaf Irish Cream
Type                              Decaf
Name: 356, dtype: object

In [19]:
display(df.iloc[355])

Profit                        -119
Margin                         -32
Sales                          182
Cost of Goods Sold             214
Total Expenses                  87
Marketing                       66
Inventory                     1480
Budget Profit                  -80
Budget Margin                  -20
Budget Sales                   140
Budget COGS                    160
Date                    31/03/2019
Market                    Atlantic
Province                       PEI
City                    Summerside
Store#                         914
Market Size           Major Market
Product Type            Herbal Tea
Product                       Mint
Type                         Decaf
Name: 357, dtype: object

In [20]:
df = df.reset_index(drop = True)

In [21]:
display(df.iloc[354])

Profit                             -121
Margin                              -27
Sales                               127
Cost of Goods Sold                  154
Total Expenses                       94
Marketing                            50
Inventory                          1288
Budget Profit                      -120
Budget Margin                       -40
Budget Sales                        150
Budget COGS                         190
Date                         31/03/2019
Market                             West
Province               British Columbia
City                          Vancouver
Store#                              685
Market Size                Major Market
Product Type                     Coffee
Product               Decaf Irish Cream
Type                              Decaf
Name: 354, dtype: object

In [22]:
display(df.iloc[355])

Profit                        -119
Margin                         -32
Sales                          182
Cost of Goods Sold             214
Total Expenses                  87
Marketing                       66
Inventory                     1480
Budget Profit                  -80
Budget Margin                  -20
Budget Sales                   140
Budget COGS                    160
Date                    31/03/2019
Market                    Atlantic
Province                       PEI
City                    Summerside
Store#                         914
Market Size           Major Market
Product Type            Herbal Tea
Product                       Mint
Type                         Decaf
Name: 355, dtype: object

In [23]:
df.head()

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
0,-354,-245,17,245,126,93,1419,-240,-160,0,160,31/1/2019,Central,Ontario,Toronto,702,Small Market,Tea,Green Tea,Regular
1,-172,-44,61,105,128,95,725,-170,-50,50,100,31/1/2019,Atlantic,PEI,Charlottetown,315,Major Market,Espresso,Caffe Mocha,Regular
2,-117,-26,118,144,91,47,862,-120,-40,140,180,31/1/2019,West,British Columbia,Vancouver,685,Major Market,Coffee,Decaf Irish Cream,Decaf
3,-113,-27,180,207,86,64,965,-70,-10,140,150,31/1/2019,Atlantic,PEI,Charlottetown,845,Major Market,Herbal Tea,Mint,Decaf
4,-40,11,99,88,51,27,525,-30,10,80,70,31/1/2019,Atlantic,New Brunswick,Saint John,591,Small Market,Herbal Tea,Mint,Decaf

## Market

In [24]:
df[df["Market"] == 'North']

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
6,-39,11,99,88,50,27,525,-20,10,80,70,31/1/2019,North,Nunavut,Iqaluit,314,Small Market,Herbal Tea,Lemon,Decaf
8,-11,53,90,37,64,34,261,0,40,70,30,31/1/2019,North,Nunavut,Iqaluit,573,Small Market,Herbal Tea,Chamomile,Decaf
11,-10,53,90,37,63,34,261,0,50,80,30,31/1/2019,North,Northwest Territories,Yellowknife,4001,Small Market,Espresso,Caffe Mocha,Regular
13,-9,36,65,29,45,11,169,-10,30,50,20,31/1/2019,North,Nunavut,Iqaluit,573,Small Market,Tea,Earl Grey,Regular
15,-8,36,65,29,44,11,169,0,40,60,20,31/1/2019,North,Northwest Territories,Yellowknife,4001,Small Market,Espresso,Regular Espresso,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,53,76,148,63,40,19,1075,40,70,130,60,31/12/2020,North,Nunavut,Iqaluit,636,Small Market,Coffee,Decaf Irish Cream,Decaf
4176,55,75,135,52,38,16,327,50,70,110,40,31/12/2020,North,Northwest Territories,Hay River,4700,Small Market,Coffee,Amaretto,Regular
4178,68,71,128,49,25,13,845,70,90,140,50,31/12/2020,North,Yukon,Whitehorse,985,Small Market,Coffee,Colombian,Regular
4185,71,73,131,50,25,14,898,70,90,150,60,31/12/2020,North,Nunavut,Iqaluit,573,Small Market,Espresso,Caffe Mocha,Regular
4205,114,120,228,94,43,31,540,70,110,190,80,31/12/2020,North,Yukon,Whitehorse,985,Small Market,Herbal Tea,Chamomile,Decaf

In [25]:
df[df["Market"] == 'Prairie']

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
20,0,87,150,63,87,57,435,20,80,130,50,31/1/2019,Prairie,Alberta,Calgary,303,Major Market,Herbal Tea,Lemon,Decaf
26,7,105,180,75,98,68,522,20,100,170,70,31/1/2019,Prairie,Manitoba,Winnipeg,1001,Small Market,Espresso,Caffe Mocha,Regular
35,9,111,190,79,102,72,551,30,110,180,70,31/1/2019,Prairie,Saskatchewan,Saskatoon,239,Major Market,Espresso,Caffe Mocha,Regular
50,13,66,120,54,53,20,312,20,50,90,40,31/1/2019,Prairie,Saskatchewan,Saskatoon,239,Major Market,Herbal Tea,Lemon,Decaf
54,17,72,130,58,55,22,338,20,70,110,40,31/1/2019,Prairie,Alberta,Calgary,303,Major Market,Tea,Darjeeling,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4214,156,174,308,115,69,37,1166,110,160,260,100,31/12/2020,Prairie,Manitoba,Steinback,1401,Small Market,Coffee,Colombian,Regular
4221,181,186,341,134,64,41,690,110,160,280,120,31/12/2020,Prairie,Saskatchewan,Regina,727,Major Market,Coffee,Decaf Irish Cream,Decaf
4223,197,179,322,123,46,34,959,110,140,230,90,31/12/2020,Prairie,Alberta,Lethbridge,900,Major Market,Espresso,Caffe Mocha,Regular
4226,199,179,322,123,45,34,959,130,170,290,120,31/12/2020,Prairie,Alberta,Edmonton,404,Major Market,Coffee,Amaretto,Regular
4232,279,284,559,241,96,74,1321,240,340,620,280,31/12/2020,Prairie,Alberta,Lethbridge,900,Major Market,Coffee,Colombian,Regular

In [26]:
df[df["Market"]== "Central"]

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
0,-354,-245,17,245,126,93,1419,-240,-160,0,160,31/1/2019,Central,Ontario,Toronto,702,Small Market,Tea,Green Tea,Regular
18,-3,42,76,34,45,12,197,10,50,90,40,31/1/2019,Central,Ontario,Toronto,702,Small Market,Coffee,Colombian,Regular
22,1,87,150,63,86,57,435,40,110,180,70,31/1/2019,Central,Ontario,Ottawa,541,Small Market,Coffee,Amaretto,Regular
24,4,34,62,28,30,8,965,20,40,70,30,31/1/2019,Central,Ontario,Toronto,775,Small Market,Coffee,Decaf Irish Cream,Decaf
38,10,27,45,18,17,5,821,20,30,40,10,31/1/2019,Central,Ontario,Toronto,702,Small Market,Espresso,Caffe Mocha,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,233,251,534,250,94,70,1820,240,320,640,320,31/12/2020,Central,Quebec,Sherbrooke,773,Major Market,Espresso,Decaf Espresso,Decaf
4234,288,310,569,224,116,73,1191,170,280,490,210,31/12/2020,Central,Ontario,Waterloo,702,Small Market,Herbal Tea,Lemon,Decaf
4235,288,310,569,224,116,73,1191,190,300,520,220,31/12/2020,Central,Quebec,Sherbrooke,312,Major Market,Coffee,Colombian,Regular
4236,319,329,614,247,114,81,1744,150,240,420,180,31/12/2020,Central,Ontario,Waterloo,775,Small Market,Tea,Darjeeling,Regular
4240,321,329,614,247,113,81,1744,320,420,730,310,31/12/2020,Central,Quebec,Sherbrooke,708,Major Market,Espresso,Caffe Mocha,Regular

In [27]:
df[df["Market"]== "Atlantic"]

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
1,-172,-44,61,105,128,95,725,-170,-50,50,100,31/1/2019,Atlantic,PEI,Charlottetown,315,Major Market,Espresso,Caffe Mocha,Regular
3,-113,-27,180,207,86,64,965,-70,-10,140,150,31/1/2019,Atlantic,PEI,Charlottetown,845,Major Market,Herbal Tea,Mint,Decaf
4,-40,11,99,88,51,27,525,-30,10,80,70,31/1/2019,Atlantic,New Brunswick,Saint John,591,Small Market,Herbal Tea,Mint,Decaf
5,-39,11,99,88,50,27,525,-30,10,120,110,31/1/2019,Atlantic,New Brunswick,Moncton,505,Small Market,Coffee,Decaf Irish Cream,Decaf
7,-23,63,126,63,86,57,435,-10,60,120,60,31/1/2019,Atlantic,Newfoundland,St. John's,2001,Major Market,Espresso,Caffe Mocha,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,321,360,697,294,144,111,1838,170,300,540,240,31/12/2020,Atlantic,Nova Scotia,Amherst,6000,Small Market,Tea,Earl Grey,Regular
4242,402,420,745,279,149,97,2642,250,370,620,250,31/12/2020,Atlantic,PEI,Montague,315,Major Market,Coffee,Colombian,Regular
4243,459,453,796,294,144,111,1727,210,320,540,220,31/12/2020,Atlantic,PEI,Montague,631,Major Market,Herbal Tea,Lemon,Decaf
4244,463,407,700,250,95,70,723,320,400,640,240,31/12/2020,Atlantic,PEI,Montague,518,Major Market,Espresso,Regular Espresso,Regular
4245,579,443,543,67,53,22,-3534,360,390,450,60,31/12/2020,Atlantic,Newfoundland,Paradise,2500,Major Market,Coffee,Colombian,Regular

In [28]:
df[df["Market"]=="West"]

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,Budget COGS,Date,Market,Province,City,Store#,Market Size,Product Type,Product,Type
2,-117,-26,118,144,91,47,862,-120,-40,140,180,31/1/2019,West,British Columbia,Vancouver,685,Major Market,Coffee,Decaf Irish Cream,Decaf
19,-2,50,145,95,52,30,608,30,70,180,110,31/1/2019,West,British Columbia,Vancouver,685,Major Market,Coffee,Amaretto,Regular
21,0,87,150,63,87,57,435,20,90,150,60,31/1/2019,West,British Columbia,Kelowna,670,Major Market,Coffee,Decaf Irish Cream,Decaf
51,16,72,130,58,56,22,338,40,90,150,60,31/1/2019,West,British Columbia,Kelowna,670,Major Market,Espresso,Decaf Espresso,Decaf
55,17,145,250,105,128,95,725,20,140,240,100,31/1/2019,West,British Columbia,Vancouver,685,Major Market,Espresso,Caffe Mocha,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4227,199,179,322,123,45,34,959,110,130,220,90,31/12/2020,West,British Columbia,Kelowna,670,Major Market,Tea,Darjeeling,Regular
4229,233,251,534,250,94,70,1820,160,240,480,240,31/12/2020,West,British Columbia,Kelowna,670,Major Market,Espresso,Caffe Latte,Regular
4233,279,284,559,241,96,74,1321,170,260,480,220,31/12/2020,West,British Columbia,Kelowna,670,Major Market,Herbal Tea,Lemon,Decaf
4237,321,329,614,247,113,81,1744,210,310,550,240,31/12/2020,West,British Columbia,Kelowna,670,Major Market,Espresso,Decaf Espresso,Decaf
4241,402,420,745,279,149,97,2642,350,500,830,330,31/12/2020,West,British Columbia,Kelowna,670,Major Market,Coffee,Colombian,Regular

# Province

In [29]:
df["Province"].unique()

array(['Ontario', 'PEI', 'British Columbia', 'New Brunswick', 'Nunavut',
       'Newfoundland', 'Northwest Territories', 'Alberta', 'Nova Scotia',
       'Manitoba', 'Yukon', 'Saskatchewan', 'Quebec'], dtype=object)

In [30]:
len(df[df["Province"]=="Ontario"])

527

In [31]:
#Number of stores in PEI province

len(df[df["Province"]=="PEI"])

191

In [32]:
#Number of stores in "British Columbia" province

len(df[df["Province"]=="British Columbia"])

504

In [33]:
#Number of stores in "New Brunswick" province

len(df[df["Province"]=="New Brunswick"])

456

In [34]:
#Number of stores in "Nunavut" province

len(df[df["Province"]=="Nunavut"])

216

In [35]:
#Number of stores in "Newfoundland" province

len(df[df["Province"]=="Newfoundland"])

360

In [36]:
#Number of stores in "Northwest Territories" province

len(df[df["Province"]=="Northwest Territories"])

168

In [37]:
#Number of stores in "Alberta" province

len(df[df["Province"]=="Alberta"])

432

In [38]:
#Number of stores in "Nova Scotia" province

len(df[df["Province"]=="Nova Scotia"])

456

In [39]:
#Number of stores in "Manitoba" province

len(df[df["Province"]=="Manitoba"])

168

In [40]:
#Number of stores in "Yukon" province

len(df[df["Province"]=="Yukon"])

168

In [41]:
#Number of stores in "Saskatchewan" province

len(df[df["Province"]=="Saskatchewan"])

216

In [42]:
#Number of stores in "Quebec" province

len(df[df["Province"]=="Quebec"])

384

# Store Number

In [43]:
df["Store#"].unique()

array([ 702,  315,  685,  845,  591,  505,  314, 2001,  573, 4001,  417,
        303,  670,  541,  775, 6300, 1001, 2500, 6520,  504,  239,  580,
       6000,  918,  503,  971,  405,  954,  754,  985,  225,  404,  863,
        337,  636,  772,  660,  217,  347,  708,  630,  309,  646,  312,
        773,  607,  631,  716,  585,  318,  816,  727,  305,  350,  786,
        850,  407,  847,  518,  815,  917,  914,  550,  598,  941,  813,
        561,  321,  224,  516,  965,  718,  904, 2900,  690,  212,  618,
        352,  370, 6200,  386, 2850, 2050, 1200, 4200,  620, 4500,  450,
       2300,  510,  635,  599, 1250,  915,  480,  525,  640, 1401, 4700,
       2370,  535,  900], dtype=int64)

# City

In [44]:
len(df['City'].unique())

51

In [45]:
t=df.groupby(['Market','Province','City','Store#','Product Type'])['Product'].count().reset_index()
t

       Market          Province        City  Store# Product Type  Product
0    Atlantic     New Brunswick    Bathurst     580       Coffee       16
1    Atlantic     New Brunswick    Bathurst     580     Espresso       25
2    Atlantic     New Brunswick    Bathurst     580   Herbal Tea       17
3    Atlantic     New Brunswick  Fredricton     550       Coffee       18
4    Atlantic     New Brunswick  Fredricton     550     Espresso       23
..        ...               ...         ...     ...          ...      ...
657      West  British Columbia   Vancouver     685          Tea       10
658      West  British Columbia    Victoria     690       Coffee       15
659      West  British Columbia    Victoria     690     Espresso       15
660      West  British Columbia    Victoria     690   Herbal Tea       15
661      West  British Columbia    Victoria     690          Tea       17

[662 rows x 6 columns]

In [46]:
t1=df.groupby(['Store#','Product Type'])['Product'].count().reset_index()
t1

     Store# Product Type  Product
0       212     Espresso        5
1       212   Herbal Tea        2
2       212          Tea        5
3       217       Coffee        5
4       217     Espresso        3
..      ...          ...      ...
383    6300          Tea       18
384    6520       Coffee        8
385    6520     Espresso       13
386    6520   Herbal Tea        8
387    6520          Tea       12

[388 rows x 3 columns]

In [47]:
len(df['Store#'].unique())

102

In [48]:
df['Margin Corrected']=df['Sales']-df['Cost of Goods Sold']

In [49]:
df['Margin']

0      -245
1       -44
2       -26
3       -27
4        11
       ...
4241    420
4242    420
4243    453
4244    407
4245    443
Name: Margin, Length: 4246, dtype: int64

In [50]:
df["Margin Corrected"]

0      -228
1       -44
2       -26
3       -27
4        11
       ...
4241    466
4242    466
4243    502
4244    450
4245    476
Name: Margin Corrected, Length: 4246, dtype: int64

In [51]:
df["Profit Corrected"] = df['Margin Corrected'] - df['Total Expenses']

In [52]:
df['Profit']

0      -354
1      -172
2      -117
3      -113
4       -40
       ...
4241    402
4242    402
4243    459
4244    463
4245    579
Name: Profit, Length: 4246, dtype: int64

In [53]:
df["Profit Corrected"]

0      -354
1      -172
2      -117
3      -113
4       -40
       ...
4241    317
4242    317
4243    358
4244    355
4245    423
Name: Profit Corrected, Length: 4246, dtype: int64

In [54]:
df.head()

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,...,Market,Province,City,Store#,Market Size,Product Type,Product,Type,Margin Corrected,Profit Corrected
0,-354,-245,17,245,126,93,1419,-240,-160,0,...,Central,Ontario,Toronto,702,Small Market,Tea,Green Tea,Regular,-228,-354
1,-172,-44,61,105,128,95,725,-170,-50,50,...,Atlantic,PEI,Charlottetown,315,Major Market,Espresso,Caffe Mocha,Regular,-44,-172
2,-117,-26,118,144,91,47,862,-120,-40,140,...,West,British Columbia,Vancouver,685,Major Market,Coffee,Decaf Irish Cream,Decaf,-26,-117
3,-113,-27,180,207,86,64,965,-70,-10,140,...,Atlantic,PEI,Charlottetown,845,Major Market,Herbal Tea,Mint,Decaf,-27,-113
4,-40,11,99,88,51,27,525,-30,10,80,...,Atlantic,New Brunswick,Saint John,591,Small Market,Herbal Tea,Mint,Decaf,11,-40

In [55]:
#Creating new column for date in correct datetime format

df['Date Corrected'] = pd.to_datetime(df['Date'])

In [56]:
df.head()

,Profit,Margin,Sales,Cost of Goods Sold,Total Expenses,Marketing,Inventory,Budget Profit,Budget Margin,Budget Sales,...,Province,City,Store#,Market Size,Product Type,Product,Type,Margin Corrected,Profit Corrected,Date Corrected
0,-354,-245,17,245,126,93,1419,-240,-160,0,...,Ontario,Toronto,702,Small Market,Tea,Green Tea,Regular,-228,-354,2019-01-31
1,-172,-44,61,105,128,95,725,-170,-50,50,...,PEI,Charlottetown,315,Major Market,Espresso,Caffe Mocha,Regular,-44,-172,2019-01-31
2,-117,-26,118,144,91,47,862,-120,-40,140,...,British Columbia,Vancouver,685,Major Market,Coffee,Decaf Irish Cream,Decaf,-26,-117,2019-01-31
3,-113,-27,180,207,86,64,965,-70,-10,140,...,PEI,Charlottetown,845,Major Market,Herbal Tea,Mint,Decaf,-27,-113,2019-01-31
4,-40,11,99,88,51,27,525,-30,10,80,...,New Brunswick,Saint John,591,Small Market,Herbal Tea,Mint,Decaf,11,-40,2019-01-31

In [57]:
df.dtypes

Profit                         int64
Margin                         int64
Sales                          int64
Cost of Goods Sold             int64
Total Expenses                 int64
Marketing                      int64
Inventory                      int64
Budget Profit                  int64
Budget Margin                  int64
Budget Sales                   int64
Budget COGS                    int64
Date                          object
Market                        object
Province                      object
City                          object
Store#                         int64
Market Size                   object
Product Type                  object
Product                       object
Type                          object
Margin Corrected               int64
Profit Corrected               int64
Date Corrected        datetime64[ns]
dtype: object

In [58]:
df.to_csv("Coffee Cup1.csv")